title: Hayden King
keywords:
  - application
  - software
  - developer
  - architect
  - aws
  - cloud
  - etl
  - cyber
  - security
description: >- # this means to ignore newlines until "baseurl:"
  Hayden's Profile Card with links to Twitter, Github, LinkedIn, and my blog
  Over 8 years developing software solutions in many different industries with both on-premise and cloud solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.haydenk.com" # the base hostname & protocol for your site, e.g. http://example.com

sass:
  sass_dir: _sass
  style: expanded

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: ['development']
  blanklines: false
  profile: false
  startings: []

exclude:
  - Dockerfile
  - _sass
  - cfn
  - .idea