AWSTemplateFormatVersion: '2010-09-09'
Description: haydenk.com Deployment Stack
Parameters:
  WebsiteS3Bucket:
    Type: String
  PrimaryDomain:
    Type: String
  SecondaryDomain:
    Type: String
  CertificateArn:
    Type: String
  HostedZone:
    Type: String
    Default: Z56MR00FY1VMM
Resources:
  WebS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebsiteS3Bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  WebS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            NotPrincipal:
              AWS: !Ref WebsiteCloudfrontOriginId
            Action:
              - 's3:GetObject'
            Resource:
              - Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Fn::GetAtt:
                        - WebS3Bucket
                        - Arn
                    - '/*'
          - Effect: Allow
            Principal:
              AWS: !Ref WebsiteCloudfrontOriginId
            Action:
              - 's3:GetObject'
            Resource:
              - Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Fn::GetAtt:
                        - WebS3Bucket
                        - Arn
                    - '/*'

  WebsiteCloudfrontOriginId:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref WebS3Bucket
  WebsiteCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref PrimaryDomain
          - !Ref SecondaryDomain
        CacheBehaviors:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
          SmoothStreaming: false
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        IPV6Enabled: true
        Origins:
          - !Ref WebS3Bucket
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          CloudFrontDefaultCertificate: false
          IamCertificateId: String
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only

  PrimaryDomainRecordV4:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref PrimaryDomain
      Type: A
      AliasTarget:
        DNSName: !Ref WebsiteCloudFront
        EvaluateTargetHealth: true

  PrimaryDomainRecordV6:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref PrimaryDomain
      Type: AAAA
      AliasTarget:
        DNSName: !Ref WebsiteCloudFront
        EvaluateTargetHealth: true

  SecondaryDomainRecordV4:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref SecondaryDomain
      Type: A
      AliasTarget:
        DNSName: !Ref WebsiteCloudFront
        EvaluateTargetHealth: true

  SecondaryDomainRecordV6:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref SecondaryDomain
      Type: AAAA
      AliasTarget:
        DNSName: !Ref WebsiteCloudFront
        EvaluateTargetHealth: true

#  FetchLambdaRole:
#    Type: 'AWS::IAM::Role'
#    Properties:
#      AssumeRolePolicyDocument:
#        Version: 2012-10-17
#        Statement:
#          - Effect: Allow
#            Principal:
#              Service:
#                - lambda.amazonaws.com
#            Action:
#              - 'sts:AssumeRole'
#      Path: /service-role/
#      Policies:
#        - PolicyName: ConedTcisLambdaExecutionPolicy
#          PolicyDocument:
#            Version: 2012-10-17
#            Statement:
#              - Effect: Allow
#                Action: 'logs:CreateLogGroup'
#                Resource:
#                  - Fn::Join:
#                      - ':'
#                      - - 'arn:aws:logs'
#                        - !Ref AWS::Region
#                        - !Ref AWS::AccountId
#                        - '*'
#              - Effect: Allow
#                Action:
#                  - 'logs:CreateLogStream'
#                  - 'logs:PutLogEvents'
#                Resource:
#                  - Fn::Join:
#                      - ':'
#                      - - 'arn:aws:logs'
#                        - !Ref AWS::Region
#                        - !Ref AWS::AccountId
#                        - '*'
#              - Effect: Allow
#                Action: 'logs:CreateLogGroup'
#                Resource:
#                  - Fn::Join:
#                      - ':'
#                      - - 'arn:aws:logs'
#                        - !Ref AWS::Region
#                        - !Ref AWS::AccountId
#                        - 'log-group'
#                        - Fn::Join:
#                            - '/'
#                            - - '/aws/lambda'
#                              - 'coned-tcis-fetch'
#                        - '*'
#        - PolicyName: ConedTcisSSMAccessPolicy
#          PolicyDocument:
#            Version: 2012-10-17
#            Statement:
#              - Effect: Allow
#                Action: 'ssm:GetParametersByPath'
#                Resource:
#                  - Fn::Join:
#                      - ':'
#                      - - 'arn:aws:ssm'
#                        - !Ref AWS::Region
#                        - !Ref AWS::AccountId
#                        - Fn::Join:
#                            - '/'
#                            - - 'parameter'
#                              - '*/coned/tcis'
#                  - Fn::Join:
#                      - ':'
#                      - - 'arn:aws:ssm'
#                        - !Ref AWS::Region
#                        - !Ref AWS::AccountId
#                        - Fn::Join:
#                            - '/'
#                            - - 'parameter'
#                              - '*/rds/level5'
#              - Effect: Allow
#                Action: 'ssm:DescribeParameters'
#                Resource: '*'
#        - PolicyName: ConedTcisS3AccessPolicy
#          PolicyDocument:
#            Version: 2012-10-17
#            Statement:
#              - Effect: Allow
#                Action:
#                  - 's3:ListBucket'
#                  - 's3:GetObject'
#                  - 's3:PutObject'
#                  - 's3:DeleteObject'
#                Resource:
#                  - Fn::Join:
#                      - ''
#                      - - 'arn:aws:s3:::'
#                        - !Ref DropBucketName
#                  - Fn::Join:
#                      - ''
#                      - - 'arn:aws:s3:::'
#                        - !Ref DropBucketName
#                        - '/*'
#        - PolicyName: ConedTcisDynamoDBPolicy
#          PolicyDocument:
#            Version: 2012-10-17
#            Statement:
#              - Effect: Allow
#                Action: 'dynamodb:PutItem'
#                Resource:
#                  Fn::GetAtt:
#                    - FetchedDataTable
#                    - Arn
#  LambdaProcessFunction:
#    Type: 'AWS::Lambda::Function'
#    Properties:
#      Code:
#        S3Bucket: !Ref LambdaCodeBucket
#        S3Key: !Ref ProcessLambdaKey
#      Description: |
#        Processes the data fetched from TCIS
#        and saved to an S3 object in level5-data bucket
#        Triggered by: DynamoDB insert
#      Environment:
#        Variables:
#          DROP_BUCKET: !Ref DropBucketName
#          LOG_LEVEL: !Ref LogLevel
#          TIME_ZONE: !Ref TimeZone
#          DB_SSM_PATH: !Ref TcisProcessRdsSsmPath
#      FunctionName: tcis-process-fetch
#      Handler: lambda_function.lambda_handler
#      MemorySize: 256
#      Role:
#        Fn::GetAtt:
#          - ProcessLambdaRole
#          - Arn
#      Runtime: python3.8
#      Timeout: 60
#Outputs:
#  FetchLambdaRole:
#    Description: "The IAM role for the Coned TCIS Fetch Lambda"
#    Value: !Ref FetchLambdaRole
#    Export:
#      Name:
#        Fn::Sub: "${AWS::StackName}-FetchLambdaRoleArn"
#  FetchLambdaArn:
#    Description: "Coned TCIS Fetch Lambda"
#    Value:
#      Fn::GetAtt:
#        - LambdaFetchFunction
#        - Arn
#    Export:
#      Name:
#        Fn::Sub: "${AWS::StackName}-LambdaFetchFunction"
