AWSTemplateFormatVersion: '2010-09-09'
Description: haydenk.com Deployment Stack
Parameters:
  WebsiteS3Bucket:
    Type: String
  PrimaryDomain:
    Type: String
  SecondaryDomain:
    Type: String
  CertificateId:
    Type: String
  HostedZone:
    Type: String
Resources:
  WebS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebsiteS3Bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  WebS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            NotPrincipal:
              AWS:
                Fn::Join:
                  - ' '
                  - - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity'
                    - !Ref WebsiteCloudfrontOriginId
            Action:
              - 's3:GetObject'
            Resource:
              - Fn::Join:
                  - '/'
                  - - Fn::GetAtt: WebS3Bucket.Arn
                    - '*'
          - Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ' '
                  - - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity'
                    - !Ref WebsiteCloudfrontOriginId
            Action:
              - 's3:GetObject'
            Resource:
              - Fn::Join:
                  - '/'
                  - - Fn::GetAtt: WebS3Bucket.Arn
                    - '*'

  WebsiteCloudfrontOriginId:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref WebS3Bucket

  WebsiteCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref PrimaryDomain
          - !Ref SecondaryDomain
        DefaultCacheBehavior:
          TargetOriginId: !Ref WebS3Bucket
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
          SmoothStreaming: false
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - Id: !Ref WebS3Bucket
            DomainName:
              Fn::Join:
                - '.'
                - - !Ref WebS3Bucket
                  - 's3'
                  - !Ref AWS::Region
                  - 'amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - '/'
                  - - 'origin-access-identity'
                    - 'cloudfront'
                    - !Ref WebsiteCloudfrontOriginId
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn:
            Fn::Join:
              - ':'
              - - 'arn:aws:acm'
                - !Ref AWS::Region
                - !Ref AWS::AccountId
                - !Join ['/', ['certificate', !Ref CertificateId]]
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only

  PrimaryDomainRecordV4:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref PrimaryDomain
      Type: A
      AliasTarget:
        HostedZoneId: 'Z2FDTNDATAQYW2'
        DNSName: !GetAtt WebsiteCloudFront.DomainName
        EvaluateTargetHealth: true

  PrimaryDomainRecordV6:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref PrimaryDomain
      Type: AAAA
      AliasTarget:
        HostedZoneId: 'Z2FDTNDATAQYW2'
        DNSName: !GetAtt WebsiteCloudFront.DomainName
        EvaluateTargetHealth: true

  SecondaryDomainRecordV4:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref SecondaryDomain
      Type: A
      AliasTarget:
        HostedZoneId: 'Z2FDTNDATAQYW2'
        DNSName: !GetAtt WebsiteCloudFront.DomainName
        EvaluateTargetHealth: true

  SecondaryDomainRecordV6:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref SecondaryDomain
      Type: AAAA
      AliasTarget:
        HostedZoneId: 'Z2FDTNDATAQYW2'
        DNSName: !GetAtt WebsiteCloudFront.DomainName
        EvaluateTargetHealth: true
