name: Build and Deploy Jekyll

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll Site
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build
          find _site -type f -exec gzip -v9 {} \; -exec mv -v {}.gz {} \;

      - name: Test Jekyll Site
        run: bundle exec htmlproofer ./_site --disable-external

      - name: Upload Jekyll Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: ./_site

      - name: Upload Cloudformation Template Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cfn
          path: ./cfn

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get ACM Certificate ARN
        env:
          CERTIFICATE_ARN: $(aws acm list-certificates --output text | grep www.haydenk.com | awk '{print $2}')
        run: echo $CERTIFICATE_ARN

      - name: Print current directory after getting artifacts
        shell: bash
        run: ls -lR
