name: Deploy haydenk.com

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      PRIMARY_DOMAIN: www.haydenk.com
      SECONDARY_DOMAIN: haydenk.com

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Cloudformation Stack
        id: haydenk-com-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: haydenk-com-stack
          capabilities: "CAPABILITY_IAM,CAPABILITY_NAMED_IAM"
          template: website-stack.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            WebsiteS3Bucket=${{ secrets.WEBSITE_BUCKET_NAME }},
            HostedZone=${{ secrets.HOSTED_ZONE_ID }},
            CertificateId=${{ secrets.ACM_CERTIFICATE_ID }},
            PrimaryDomain=${{ env.PRIMARY_DOMAIN }},
            SecondaryDomain=${{ env.SECONDARY_DOMAIN }}
