name: Build and Deploy Jekyll

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll Site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --config _config.yml,_config_deploy.yml

      - name: Test Jekyll Site
        run: bundle exec htmlproofer ./_site --disable-external

      - name: Upload Jekyll Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: ./_site

      - name: Upload Cloudformation Template Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cfn
          path: ./cfn

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    env:
      WEBSITE_BUCKET_NAME: haydenk-com-544e760
      PRIMARY_DOMAIN: www.haydenk.com
      SECONDARY_DOMAIN: haydenk.com
      AWS_REGION: us-east-1

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${AWS_REGION}

      - name: Deploy Cloudformation Stack
        run: |
          aws cloudformation deploy \
              --stack-name haydenk-com-stack \
              --template-file cfn/website-stack.yml \
              --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
              --parameter-overrides \
                WebsiteS3Bucket=$WEBSITE_BUCKET_NAME \
                HostedZone=$HOSTED_ZONE_ID \
                CertificateId=$ACM_CERTIFICATE_ID \
                PrimaryDomain=$PRIMARY_DOMAIN \
                SecondaryDomain=$SECONDARY_DOMAIN
